sudo: required

language: c++

services:
  - docker

before_install:
  - docker pull gitlab-registry.cern.ch/asinica/dqmgui-ci-worker

script:
  - docker run -i -t --name dqmgui -v ${PWD}:/data/srv/BUILD gitlab-registry.cern.ch/asinica/dqmgui-ci-worker /bin/sh -c '. /data/srv/current/apps/dqmgui/128/etc/profile.d/env.sh && for s in /data/srv/current/*/*/*/*/*/etc/profile.d/init.sh; do . $s; done && cd BUILD && monDistPatch -s DQM && cd .. && /data/srv/current/config/dqmgui/manage -f dev start "I did read documentation"'
